//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChefJeeves
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipeingredient
    {
        public int RECIPE_ID { get; set; }
        public string INGREDIENT_NAME { get; set; }
        public float QUANTITY { get; set; }
        public string UNIT_ABBREVIATION { get; set; }
    
        public virtual ingredient ingredient { get; set; }
        public virtual measurement measurement { get; set; }
        public virtual recipe recipe { get; set; }
    }
}
