USE `chefjeeves`;

DROP TABLE IF EXISTS `AccountRecipe`;
DROP TABLE IF EXISTS `RecipeIngredient`;
DROP TABLE IF EXISTS `Recipe`;
DROP TABLE IF EXISTS `Measurement`;
DROP TABLE IF EXISTS `UserIngredient`;
DROP TABLE IF EXISTS `Ingredient`;
DROP TABLE IF EXISTS `Account`;

CREATE TABLE `Account` (
	`EMAIL` varchar(64) NOT NULL,
	`FIRST_NAME` varchar(64) NOT NULL,
	`LAST_NAME` varchar(64) NOT NULL,
	`PASSCODE` varchar(512) NOT NULL,
	`SALT` float NOT NULL,
	`IS_ACTIVE_USER` tinyint(1) NOT NULL,
	`IS_ADMIN` tinyint(1) NOT NULL,
  PRIMARY KEY (`EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Recipe` (
	`RECIPE_ID` int(11) NOT NULL AUTO_INCREMENT,
	`RECIPE_NAME` varchar(64) NOT NULL,
	`PREPARATION` text NOT NULL,
	`IS_VALID_RECIPE` tinyint(1) NOT NULL,
  PRIMARY KEY (`RECIPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `AccountRecipe` (
	`EMAIL` varchar(64) NOT NULL,
	`RECIPE_ID` int(11) NOT NULL,
	PRIMARY KEY (`EMAIL`,`RECIPE_ID`),
	CONSTRAINT `AccountRecipe_EMAIL` FOREIGN KEY (`EMAIL`) REFERENCES `Account` (`EMAIL`) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT `AccountRecipe_RECIPE_ID` FOREIGN KEY (`RECIPE_ID`) REFERENCES `Recipe` (`RECIPE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Ingredient` (
	`INGREDIENT_NAME` varchar(64) NOT NULL,
	`IS_VALID_INGREDIENT` tinyint(1) NOT NULL,
	PRIMARY KEY (`INGREDIENT_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Measurement` (
	`UNIT_ABBREVIATION` varchar(64) NOT NULL,
	`UNIT_NAME` varchar(64) NOT NULL,
	PRIMARY KEY (`UNIT_ABBREVIATION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `RecipeIngredient` (
	`RECIPE_ID` int(11) NOT NULL,
	`INGREDIENT_NAME` varchar(64) NOT NULL,
	`QUANTITY` float NOT NULL,
	`UNIT_ABBREVIATION` varchar(64),
	PRIMARY KEY (`RECIPE_ID`,`INGREDIENT_NAME`),
	CONSTRAINT `RecipeIngredient_RECIPE_ID` FOREIGN KEY (`RECIPE_ID`) REFERENCES `Recipe` (`RECIPE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT `RecipeIngredient_INGREDIENT_NAME` FOREIGN KEY (`INGREDIENT_NAME`) REFERENCES `Ingredient` (`INGREDIENT_NAME`) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT `RecipeIngredient_UNIT_ABBREVIATION` FOREIGN KEY (`UNIT_ABBREVIATION`) REFERENCES `Measurement` (`UNIT_ABBREVIATION`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `UserIngredient` (
	`EMAIL` varchar(64) NOT NULL,
	`INGREDIENT_NAME` varchar(64) NOT NULL,
	PRIMARY KEY (`EMAIL`,`INGREDIENT_NAME`),
	CONSTRAINT `UserIngredient_EMAIL` FOREIGN KEY (`EMAIL`) REFERENCES `Account` (`EMAIL`) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT `UserIngredient_INGREDIENT_NAME` FOREIGN KEY (`INGREDIENT_NAME`) REFERENCES `Ingredient` (`INGREDIENT_NAME`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `account` (`EMAIL`,`FIRST_NAME`,`LAST_NAME`,`PASSCODE`,`SALT`,`IS_ACTIVE_USER`,`IS_ADMIN`) VALUES ('john.smith@email.com','John','Smith','password',1.0,1,1);
INSERT INTO `ingredient`(`INGREDIENT_NAME`,`IS_VALID_INGREDIENT`) VALUES ('egg',1);
INSERT INTO `ingredient`(`INGREDIENT_NAME`,`IS_VALID_INGREDIENT`) VALUES ('butter',1);
INSERT INTO `ingredient`(`INGREDIENT_NAME`,`IS_VALID_INGREDIENT`) VALUES ('bacon',1);
INSERT INTO `ingredient`(`INGREDIENT_NAME`,`IS_VALID_INGREDIENT`) VALUES ('flour',1);
INSERT INTO `ingredient`(`INGREDIENT_NAME`,`IS_VALID_INGREDIENT`) VALUES ('salt',1);
INSERT INTO `ingredient`(`INGREDIENT_NAME`,`IS_VALID_INGREDIENT`) VALUES ('pepper',1);
INSERT INTO `ingredient`(`INGREDIENT_NAME`,`IS_VALID_INGREDIENT`) VALUES ('tomato',1);
INSERT INTO `ingredient`(`INGREDIENT_NAME`,`IS_VALID_INGREDIENT`) VALUES ('brown bean',1);
INSERT INTO `ingredient`(`INGREDIENT_NAME`,`IS_VALID_INGREDIENT`) VALUES ('strawberry',1);
INSERT INTO `ingredient`(`INGREDIENT_NAME`,`IS_VALID_INGREDIENT`) VALUES ('orange',1);
